version: '3.1'

services:

  postgres:
    restart: always
    container_name: go_crud
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data